# Generated by Django 3.2.9 on 2021-12-05 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_products_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
