# Generated by Django 4.0 on 2021-12-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Phone',
            new_name='phone',
        ),
    ]
