# Generated by Django 4.0.1 on 2022-01-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_address_order_phone_order_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
